// Generated by CoffeeScript 1.6.2
(function() {
  var RemoteClient,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  RemoteClient = (function(_super) {
    __extends(RemoteClient, _super);

    /*
    */


    function RemoteClient(_source) {
      this._source = _source;
      this._onOpen = __bind(this._onOpen, this);
      this._onMessage = __bind(this._onMessage, this);
      RemoteClient.__super__.constructor.call(this);
      this._s = new SockJS(this._source);
      this._s.onmessage = this._onMessage;
      this._s.onopen = this._onOpen;
    }

    /*
    */


    RemoteClient.prototype.handle = function(data) {
      return this._s.send(JSON.stringify(data));
    };

    /*
    */


    RemoteClient.prototype._onMessage = function(message) {
      var payload;

      payload = JSON.parse(message.data);
      return this.dispatch(payload);
    };

    /*
    */


    RemoteClient.prototype._onOpen = function() {
      return this.dispatch({
        event: "platform",
        data: String(navigator.userAgent)
      });
    };

    return RemoteClient;

  })(require("../../common/clients/base"));

  module.exports = RemoteClient;

}).call(this);
