// Generated by CoffeeScript 1.6.2
(function() {
  var BaseClient, CopyClient, events, _id,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  events = require("events");

  CopyClient = require("./copy");

  _id = BaseClient = (function() {
    /*
    */
    function BaseClient() {
      this.handle = __bind(this.handle, this);      this._id = Number(Date.now()) + "_" + Math.round(Math.random() * 999999999);
      this._observers = [];
    }

    /*
    */


    BaseClient.prototype.init = function() {};

    /*
     copies events from / to this client
    */


    BaseClient.prototype.copy = function() {
      return new CopyClient(this);
    };

    /*
    */


    BaseClient.prototype.dispatch = function(data) {
      var observer, _i, _len, _ref, _results;

      if (!data.origin) {
        data.origin = this._id;
      }
      _ref = this._observers;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        observer = _ref[_i];
        _results.push(observer(data));
      }
      return _results;
    };

    /*
    */


    BaseClient.prototype.handle = function(data) {};

    /*
    */


    BaseClient.prototype.observe = function(observer) {
      if (!this._initialized) {
        this._initialized = true;
        this.init();
      }
      this._observers.push(observer);
      return {
        dispose: function() {
          var i;

          i = this._observers.indexOf(observer);
          if (!~i) {
            return;
          }
          return this._observers.splice(i, 1);
        }
      };
    };

    return BaseClient;

  })();

  module.exports = BaseClient;

}).call(this);
