// Generated by CoffeeScript 1.6.2
(function() {
  var CommandsClient,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  CommandsClient = (function(_super) {
    __extends(CommandsClient, _super);

    /*
    */


    function CommandsClient() {
      this.handle = __bind(this.handle, this);      CommandsClient.__super__.constructor.call(this);
      this._commands = {};
      this.observe(this.handle);
    }

    /*
    */


    CommandsClient.prototype.register = function(commands, listener) {
      var command, _i, _len, _ref, _results;

      _ref = commands.split(" ");
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        command = _ref[_i];
        _results.push(this._commands[command] = listener);
      }
      return _results;
    };

    /*
    */


    CommandsClient.prototype.handle = function(data) {
      var listener, _ref;

      listener = (_ref = this._commands[data.event]) != null ? _ref : this._commands["*"];
      if (!listener) {
        return;
      }
      return listener(data);
    };

    return CommandsClient;

  })(require("./base"));

  module.exports = CommandsClient;

}).call(this);
