// Generated by CoffeeScript 1.6.2
(function() {
  var CopyClient;

  CopyClient = (function() {
    /*
    */
    function CopyClient(_client) {
      this._client = _client;
      this.filter(function() {
        return true;
      });
    }

    /*
    */


    CopyClient.prototype.filter = function(_filter) {
      this._filter = _filter;
      return this;
    };

    /*
    */


    CopyClient.prototype.to = function(client) {
      var _this = this;

      this._observer = this._client.observe(function(data) {
        if (!_this._filter(data)) {
          return;
        }
        return client.handle(data);
      });
      return this;
    };

    /*
    */


    CopyClient.prototype.from = function(client) {
      var _this = this;

      this._observer = client.observe(function(data) {
        if (!_this._filter(data)) {
          return;
        }
        return _this._client.handle(data);
      });
      return this;
    };

    /*
    */


    CopyClient.prototype.dispose = function() {
      var _ref;

      if ((_ref = this._observer) != null) {
        _ref.dispose();
      }
      return this._observer = void 0;
    };

    return CopyClient;

  })();

  module.exports = CopyClient;

}).call(this);
