// Generated by CoffeeScript 1.6.2
(function() {
  var _this = this;

  module.exports = function(payload) {
    return $(document).xpath(payload.data.path).trigger(payload.event);
  };

}).call(this);
