// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(payload) {
    var $e;

    $e = $(document).xpath(payload.data.path);
    $e.val(payload.data.value);
    $e.trigger("keydown");
    return $e.trigger("keyup");
  };

}).call(this);
