// Generated by CoffeeScript 1.6.2
(function() {
  var Client, client, event, findXPath, handleEvent, _i, _len, _ref;

  Client = require("../../common/clients/base");

  client = new Client();

  findXPath = require("./findXPath");

  handleEvent = function(event) {
    return client.dispatch({
      event: event.type,
      data: {
        path: event.target ? findXPath(event.target) : void 0,
        value: String($(event.target).val())
      }
    });
  };

  _ref = this._events = ["mousedown", "mouseup", "click", "keydown", "keyup"];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    event = _ref[_i];
    document.addEventListener(event, handleEvent, true);
  }

  module.exports = {
    dispatcher: client
  };

}).call(this);
