// Generated by CoffeeScript 1.6.2
(function() {
  var Client, client, handle, onEvent, _ignoreScroll;

  Client = require("../../common/clients/base");

  client = new Client();

  _ignoreScroll = false;

  onEvent = function() {
    var $d;

    if (_ignoreScroll) {
      return;
    }
    $d = $(document);
    return client.dispatch({
      event: "scroll",
      data: {
        top: $d.scrollTop(),
        left: $d.scrollLeft()
      }
    });
  };

  $(document).scroll(onEvent);

  handle = function(payload) {
    _ignoreScroll = true;
    $(document).scrollTop(payload.data.top);
    $(document).scrollLeft(payload.data.left);
    return _ignoreScroll = false;
  };

  module.exports = {
    handler: handle,
    dispatcher: client
  };

}).call(this);
