// Generated by CoffeeScript 1.6.2
(function() {
  var RemoteClient,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  RemoteClient = (function(_super) {
    __extends(RemoteClient, _super);

    /*
    */


    function RemoteClient() {
      RemoteClient.__super__.constructor.call(this);
    }

    /*
    */


    return RemoteClient;

  })(require("../../common/clients/base"));

}).call(this);
