// Generated by CoffeeScript 1.6.2
(function() {
  var fasten, type,
    _this = this;

  fasten = require("fasten")();

  type = require("type-component");

  fasten.add("actions", {
    "click": {
      call: function(path, next) {
        $(document).xpath(path).click();
        return next(null, this);
      }
    },
    "type": {
      call: function(path, value, next) {
        var $el;

        ($el = $(document).xpath(path)).val(value);
        $el.trigger("keydown");
        $el.trigger("keyup");
        return next(null, this);
      }
    },
    "next": {
      call: function(fn, next) {
        var _this = this;

        return fn(function() {
          return next(null, _this);
        });
      }
    },
    "wait": {
      call: function(fn, next) {
        var check;

        if (type(fn) === "number") {
          return setTimeout(next, fn);
        }
        check = function() {
          if (fn()) {
            next(null, _this);
          }
          return setTimeout(500, next);
        };
        return check();
      }
    },
    "visit": {
      call: function(location, next) {
        window.location = location;
        return next();
      }
    },
    "dispatch": {
      call: function(data, next) {
        return next(null, _this);
      }
    },
    "handle": {
      call: function(data, next) {
        return next(null, _this);
      }
    },
    "find": {
      call: function(path, next) {
        console.log($(document).xpath(path));
        return next(null, this);
      }
    }
  });

  module.exports = fasten.wrap("actions", {
    and: function(fn) {
      fn();
      return this;
    }
  });

}).call(this);
